api: apps/v1
kind: Deployment
metadata:
  name: gitlab-app
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab-app
    spec:
      volumes:
        - name: gitlab-config
          hostPath: /tmp/config
        - name: gitlab-logs
          hostPath: /tmp/log
        - name: gitlab-data
          hostPath: /tmp/opt
      containers:
        - name: gitlab-app
          image: gitlab/gitlab-ee:17.8.0-ee.0
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab
          volumeMounts:
            - name: gitlab-logs
              mountPath: /var/log/gitlab
          volumeMounts:
            - name: gitlab-data
              mountPath: /var/opt/gitlab
          ports:
            - containerPort: 80
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-app-service
  namespace: gitlab
spec:
  type: LoadBalancer
  selector:
    app: gitlab-app
  ports:
    - port: 80
      targetPort: 80
