
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.name = "ybenlafkS"  
    end
    
    config.vm.define "ybenlafkS" do |server|
        server.vm.hostname = "ybenlafkS"
        server.vm.network "private_network", ip: "192.168.56.110"
        server.vm.provision "shell", path: "scripts/install.sh"
    end
end