
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.hostname = "ybenlafkS"
    
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
        v.name = "ybenlafkS"
    end

    config.vm.network "private_network", ip: "192.168.56.110"
    
    config.vm.provision "shell", path: "scripts/install.sh"
end