Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_version = "20230607.0.5"

	config.vm.provider "virtualbox" do |v|
		v.memory = 1024
		v.cpus = 1
		# v.name = "rben-mou"
	end

	# K3s Server
	config.vm.define "rben-mouS" do |conf|
		conf.vm.hostname = "rben-mouS"
		conf.vm.network "private_network", ip: "192.168.56.110"
		conf.vm.provision "shell", path: "scripts/server.sh"
	end

	# K3s Agent
	config.vm.define "rben-mouSW" do |conf|
		conf.vm.hostname = "rben-mouSW"
		conf.vm.network "private_network", ip: "192.168.56.111"
		conf.vm.provision "shell", path: "scripts/agent.sh"
	end

end
